# Generated by Django 3.1.5 on 2021-02-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
