# Generated by Django 3.1.5 on 2021-02-09 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='last_name')),
                ('age', models.IntegerField(null=True, verbose_name='age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, verbose_name='gender')),
                ('nationality', models.CharField(max_length=50, null=True, verbose_name='nationality')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=50, null=True, verbose_name='state')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='city')),
                ('zip_code', models.CharField(max_length=50, null=True, verbose_name='zip code')),
                ('user_address', models.CharField(max_length=50, null=True, verbose_name='user address')),
                ('shop_title', models.CharField(max_length=50, verbose_name='Shop title')),
                ('shop_address', models.CharField(max_length=50, null=True, verbose_name='shop address')),
                ('request_approve', models.CharField(choices=[('Approved', 'Approved'), ('Cancel', 'cancel')], max_length=50, null=True, verbose_name='request_approval')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create date')),
                ('requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
