# Generated by Django 3.1.5 on 2021-02-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_coupon'),
        ('orders', '0003_auto_20210212_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkouts.coupon'),
        ),
    ]
