# Generated by Django 3.1.5 on 2021-02-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
